source 'https://github.com/Huaixing/CATMasterRepos.git'

platform :ios, '10.0'

target 'CATTextKit_Example' do
  pod 'CATTextKit', :path => '../'
  pod 'CATCommonKit', '~> 0.1.5'

  target 'CATTextKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
