use_frameworks!

platform :ios, '8.0'

target 'CATTextKit_Example' do
  pod 'CATTextKit', :path => '../'

  target 'CATTextKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
