source 'https://github.com/Huaixing/CATMasterRepos.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'CATTextKit_Example' do
  pod 'CATTextKit', :path => '../'
  pod 'CATCommonKit', '~> 0.2.0'

  target 'CATTextKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
